### ISSUE TITLE
endgame feel is not right

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#18]
I like the 40 games throwback but the sound effect doesn't fit well with the feel of the music. I think the endgame ruffle should be changed or replaced

I also think the endgame message is too long. Maybe we don't have to say "press r" or whatever.

**Comment by ebrahimebrahim** [comment]
i've heard the endgame ruffle so many times now that I am starting to like it...

**Comment by yusufmte** [comment]
lol! It's growing on me too... I have ideas for 2 other ones we could try,
I'll make and send them so we have more choice and might decide on a more
fitting one.

**Comment by yusufmte** [comment]
I tried a few different ones (and played with LMMS to make one! :D) and none of them quite felt right. I don't know if it's just because the ruffle has been there long enough, but now the ruffle is seeming very fitting. I'd be on board with just leaving it and closing this issue. What do you think?

**Comment by yusufmte** [comment]
I decreased the ruffle's volume relative to music/knocks in 833b9fb84d18c80641642b7f8838800a2b42f148 and I think it sounds a lot less out-of-place now.

**Comment by ebrahimebrahim** [comment]
I think it's good enough now! @yusufmte close if you  agree
