### ISSUE TITLE
Boulders can still be invalid sometimes

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#22]
It's quite rare but this needs to be fixed.

![Screenshot from 2020-09-24 00-09-57](https://user-images.githubusercontent.com/1879759/94100188-ed1d6780-fdfa-11ea-8a5e-687184f3f22d.png)

**Comment by ebrahimebrahim** [comment]
No, for some reason I don't think you "got it this time"

**Comment by yusufmte** [comment]
LOL
