### ISSUE TITLE
make it more intuitive that there is no holding past the throwzone

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#31]
During playtest, it was found to be nonintuitive. Sure you can't pick up rocks past the line of pebbles, and you get yelled at for that. But it felt like you could still throw rocks past the line of pebbles, until you throw a big rock and watch it plop down just past the pebble line.

Basically the thing we are visually indicating with a splayed hand cursor needs to be more clearly indicated

**Comment by yusufmte** [comment]
We can send a very quick message that says "Dropped!" or something if you
are forced to drop a rock due to carrying it over the line.

**Comment by ebrahimebrahim** [comment]
Hmm I think it's a good idea but I slightly agree with Leyi's opinion: it's too "messagy" of a way of communicating that. It would be nice to do it visually instead of polluting the screen with messages

Leyi's other ideas:
- your hand explodes into a puff of dust when it goes beyond the line. it reforms when you move it back
- another hand comes in and slaps your hand back when you move over the line with a held rock

I'm not sure... I do kinda like the simple "Dropped!"

**Comment by ebrahimebrahim** [comment]
one thought to keep in mind: we don't actually want to discourage the player from moving their hand past the line in a throw. That's fine to do right? It feels more natural.

We just want the player to see more clearly that the rock is released

So a "dropped!" message or an exploding hand seem to be not good solutions. The annoying text or explosion would make me not want to move my hand past the line, which feels restrictive.

Maybe what we need is a more obvious version of the splayed hand? Or just to make the change from normal--splayed be more impactful/obvious?

**Comment by yusufmte** [comment]
> one thought to keep in mind: we don't actually want to discourage the player from moving their hand past the line in a throw. That's fine to do right? It feels more natural.

I'm on the fence about this... One thing you can do especially with small rocks is just drag the mouse to the opposite end of the screen where the target rock, letting the drop happen for you, is and it can be pretty easy to knock rocks that way. And it doesn't really make sense physically; your hand can only get as far away from you as your arm is long, and you would have to step over the line of pebbles to do that.

So I think I'm in favor of discouraging trying to throw over the line. It feels more organic and fun when the hand stays within the bounds and when you choose the exact moment to release the rock.

If you agree with this assessment, one solution is we could even consider halting the rock altogether if you're holding it over the line (along with the "Dropped!" message). You would still be able to get it back, but it would present a clear view of what happens and you would get another chance to throw from within the bounds.

**Comment by ebrahimebrahim** [comment]
After discussing we decided that it's fine to allow the player to mess around and figure out the mechanic
