### ISSUE TITLE
zero gravity rocks can spawn overlapping

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#40]
In zero gravity challenge mode, new rocks can spawn overlapping with existing rocks.

**Comment by ebrahimebrahim** [comment]
`spawn_rocks` in `GameBase.gd` should be modified to not overlap with other rocks in the scene

when it fails to find a non-overlappy place to spawn, it should set a timer and call itself to try again later

**Comment by yusufmte** [comment]
(Take a look at the commit 1a8b1d08d133d3751b7ec913262f668deb6379ef . I'm pretty sure this is fixed and we can close the issue but want to be sure it's fixed in a good way.)
