### ISSUE TITLE
windows icon not working

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#41]
https://godot-es-docs.readthedocs.io/en/latest/getting_started/workflow/export/changing_application_icon_for_windows.html

**Comment by yusufmte** [comment]
The windows icon requires the use of a tool that needs windows or wine (https://github.com/electron/rcedit/releases).

The following was the result of using rcedit to export the game from Godot with windows (the icon worked, but the game wouldn't launch):
![WhatsApp Image 2020-09-28 at 18 22 28](https://user-images.githubusercontent.com/45940010/94499782-908bc500-01cb-11eb-8b53-2602071ad292.jpeg)

This is the result of a known error (https://github.com/godotengine/godot/issues/33466) that occurs when (1) the rcedit tool is used and (2) the pck is embedded.

So I tried to use rcedit without embedding the pck and it worked:
![WhatsApp Image 2020-09-28 at 18 26 33](https://user-images.githubusercontent.com/45940010/94499791-9b465a00-01cb-11eb-84bf-98b077c5c985.jpeg)

It peuped out the .exe and then a .pck, which I'm assuming needs to be in the same directory as the .exe for it to work.

We have three options moving forward:
(1) Try to look harder for a way to make the icon correct while also embedding the .pck
(2) Accept the unembedded .pck, and just offer a .zip containing the .exe+.pck on download for the Windows version
(3) Accept the incorrect icon, and embed the .pck

What do you think?

**Comment by ebrahimebrahim** [comment]
Not embedding the pck sounds okay

**Comment by yusufmte** [comment]
Closing this issue. We just need to remember these steps for exporting the windows executable.
