### ISSUE TITLE
Test, release, and put on itch

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#54]

**Comment by ebrahimebrahim** [comment]
Linux and mac tests are good on 8811ccd74fcd59cb232658db4102d579dc9a9af8
Will test windows soon

@yusufmte is there anything else you want to do before 1.1?

**Comment by ebrahimebrahim** [comment]
Windows test is good

Added one more commit (abc4404174b5e0ed56a4da10012d56ec9f1a5bf6) that updated a tooltip in `Strings.gd`-- not re-running mac and windows tests for this.

**Comment by ebrahimebrahim** [comment]
@yusufmte ready for 1.1.0 release if you agree

**Comment by yusufmte** [comment]
Agree! Just went through commits and tested stuff, I really like all the improvements.

**Comment by ebrahimebrahim** [comment]
release 1.1.0 tag now exists on release branch

**Comment by ebrahimebrahim** [comment]
it's up on itch and I added a link into the readme
