### ISSUE TITLE
More settings

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#7]
- music vol (when there's music)
- gravity
- total rocks given

add more here if you want them

**Comment by yusufmte** [comment]
HUD hidden by default

**Comment by ebrahimebrahim** [comment]
process for adding a setting explained here: https://github.com/ebrahimebrahim/knock-the-rock/commit/363da8f21266f04b3c9872fdb1858ad2c7e555e0

**Comment by ebrahimebrahim** [comment]
> HUD hidden by default

ah good one

We should really call it "menu" not "HUD"
I think the word HUD sounds like it would include the "rocks knocked" messages and stuff

**Comment by ebrahimebrahim** [comment]
language

(it would be fun to translate to arabic and chinese :grinning: )

**Comment by yusufmte** [comment]
Haha yes! :D

**Comment by ebrahimebrahim** [comment]
5dc4517942a6b363160fe60ef32f1279ed45a961
acdf25254834429d9a6967d7baec2d1edf078b85
f88ef57afb940223bad6dc3163c5140a5e9f2b05
71f26ff8b738e243d65d0456df76e48d989e9853
042a9dcfd777cd0d5ac7e0dc1fbb97ea26f9c7bc
6208f31c4b0ce102d6b333b5720b1bcb25260f86
02ad330435851ad5e92fc2802cd927df5e065093
