### ISSUE TITLE
rename HUD to menu

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#8]
We should really call it "menu" not "HUD"
I think the word HUD sounds like it would include the "rocks knocked" messages and stuff

_Originally posted by @ebrahimebrahim in https://github.com/ebrahimebrahim/knock-the-rock/issues/7#issuecomment-695833283_

**Comment by yusufmte** [comment]
but we currently call the main menu the menu (as in "Return to Menu")...should we also rename "menu" to "main menu"?

**Comment by ebrahimebrahim** [comment]
@yusufmte oh good point,
the toggle menu button can say "toggle **this** menu" (without the bold)

**Comment by yusufmte** [comment]
peup, nice!
