### ISSUE TITLE
Animate fireflies

### ISSUE THREAD

**Issue by yusufmte** [ebrahimebrahim/knock-the-rock#9]

**Comment by ebrahimebrahim** [comment]
or remove the fireflies

**Comment by ebrahimebrahim** [comment]
removed fireflies in 81742cc248f9fc804692634495bb553d6ccb57da
we can add a firefly animation later if you want but i'll leave that optional

**Comment by ebrahimebrahim** [comment]
A couple of problems:
- The fireflies are always in one weirdly specific place in the background, and they are very prominent and distracting. Is this "knock the rock" or is it "watch the fireflies" ... I don't know anymore!
- MenuScreen and GameBase scenes seem to have duplicated the fireflies node between each other. I think when this happens, fireflies should be its own scene (even if it's just one node) and MenuScreen and GameBase can instance that one scence

**Comment by ebrahimebrahim** [comment]
A few ideas:

(1) We could keep the "fireflies" in the menu screen only; I think that would be acceptable although I'm still in favor of not having them at all.

(2) We could just hang onto them as a game asset that we can use in future games. They are well animated.

(3) They could be some kind of easter egg thing that only shows up under specific and somewhat rare circumstances

**Comment by yusufmte** [comment]
Hmm, good ideas! :D Idea for 3: 1 in 100 times a challenge mode game starts, you instead enter special mode (a scene that inherits from challenge mode) where the rocks are 2x larger and there are fireflies.

**Comment by ebrahimebrahim** [comment]
Haha, or special mode could be triggered by knocking more rocks than you had to throw initially

**Comment by yusufmte** [comment]
That's a better idea!
